name:                try-concur-replica
version:             0.1.0.0
github:              "githubuser/try-concur-replica"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/try-concur-replica#readme>

default-extensions:
  AutoDeriveTypeable
  BangPatterns
  BinaryLiterals
  ConstraintKinds
  DataKinds
  DefaultSignatures
  DeriveDataTypeable
  DeriveFoldable
  DeriveFunctor
  DeriveGeneric
  DeriveTraversable
  EmptyDataDecls
  ExistentialQuantification
  FlexibleContexts
  FlexibleInstances
  FunctionalDependencies
  GADTs
  GeneralizedNewtypeDeriving
  InstanceSigs
  KindSignatures
  LambdaCase
  MonadFailDesugaring
  MultiParamTypeClasses
  MultiWayIf
  NamedFieldPuns
  NoImplicitPrelude
  OverloadedStrings
  PartialTypeSignatures
  PatternGuards
  PolyKinds
  RankNTypes
  RecordWildCards
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeFamilies
  TypeSynonymInstances
  ViewPatterns
  # DoAndIfThenElse

dependencies:
- base >= 4.7 && < 5
- relude
- text
- bytestring
- concur-core
- concur-replica
- replica
- wai
- wai-websockets
- websockets
- warp
- stm

library:
  source-dirs: src

executables:
  try-concur-replica-button-pusher:
    main:                Main.hs
    source-dirs:         app/ButtonPusher
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concur-replica
    - random

  try-concur-replica-phantom-event:
    main:                Main.hs
    source-dirs:         app/PhantomEvent
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concur-replica

tests:
  try-concur-replica-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-concur-replica
